### ISSUE TITLE
Scope of the ontology

### ISSUE THREAD

**Issue by FranckCo** [linked-statistics/COOS#22]
- Should we consider additional standards (CSPA, CSDA, GSDEM...)?
- Should we broaden the scope (e.g. geospatial)?

**Comment by JALinnerud** [comment]
Ideally, we would like to cover all of these, but do we have the time, in our current plan, and do we have the resources in our current group? Should we first use our time and resources doing a really good job of GAMSO, GSBPM, GSIM, getting that finished and thereby having a good starting point for the others?

**Comment by abrycsaba** [comment]
In my opinion we should concentrate on the models for statistical business process (GSBPM and GSIM) as such as this is the core activity of different statistical agencies. This is enough for the duration of this project. Taking into consideration other models e.g. GAMSO, CSPA, CSDA, GSDEM could be suggested as 'new' projects for next year.

**Comment by FranckCo** [comment]
Decided during 23/02/21 meeting: stick to GAMSO/GSBPM/GSIM for now, but keep in mind capability (CSDA, GAMSO) and roles (CSPA, GSIM).

**Comment by abrycsaba** [comment]
In the previous meetings it has been decided to concentrate on the following standards in the framework of this project: GSIM, GAMSO and GSBPM.
What are the scope of these standards, which is going to determine the scope of this project? Those are as follows:

GSBPM
•	The Generic Statistical Business Process Model (GSBPM) describes and defines the set of business processes needed to produce official statistics. It provides a standard framework and harmonised terminology to help statistical organisations to modernise their statistical production processes, as well as to share methods and components.

GSIM 
•	GSIM provides the information object framework supporting all statistical business processes such as those described in the Generic Statistical Business Process Model (GSBPM) giving the information objects agreed names, defining them, specifying their essential properties, and indicating their relationships with other information objects. It does not, however, make assumptions about the standards or technologies used to implement the model.
•	GSIM does not include information objects related to activities within an organisation such as human resources, finance, or legal functions, except to the extent that this information is used directly in statistical production. For more information on these activities see the Generic Activity Model for Statistical Organisations (GAMSO).
GAMSO
•	The GAMSO describes and defines activities that take place within a typical statistical organisation. It extends and complements the GSBPM by adding activities needed to support statistical production (i.e. activities in the areas of strategy and leadership, capability development and corporate support). In the GSBPM v5.0, some of these activities were included as overarching processes. Activities that are not directly related to the production of statistics and/or are managed at a corporate or strategic level are now included in the GAMSO (e.g. human resource management, quality management activities that are carried out at the corporate level such as development of a quality framework).
•	The GAMSO describes activities – that is, what statistical organisations do. It includes high level descriptions of these activities. On the other hand, the GSBPM focuses on the production process – it describes in more detail how statistical organisations undertake the activity of statistical production.
•	Like the GSBPM, the GAMSO aims to provide a common vocabulary and framework to support international collaboration activities. Greater value will be obtained from the GAMSO if it is applied in conjunction with the GSBPM.
As it can be seen, the summarised scope of these standards is quite broad. It covers both the main task of a NSO or any statistical organisation and also the background tasks in order to ensure the operation of the main task which is the handling of statistical business processes.
In case of information objects, the model used for describing them concentrates only on statistical business processes, their inputs and outputs and does not take into consideration of the more generic activities (not necessarily statistical ones, which means the aim of these tasks are not statistical activity but operating an organisation in general) described in GAMSO. There are some examples of information objects that are output objects of those previously mentioned background tasks in GSIM, but those are in close relation to the statistical business process e.g. provision agreement, statistical support program, information request, process method etc.
But if we consider that the generic tasks described in GAMSO also have information objects (e.g. vision, strategy, HR trainings, information standards etc) that have to be handled there might be a lack in standard information objects for this project.
The granularity of GSBPM and GAMSO also differs. GSBPM covers overarching processes, process steps and sub-processes while GAMSO only describes the field that only classifies the processes and activities (or as those are called in GAMSO activity areas and activities) to be conducted in the given are. The processes are missing so far. That might be a future task for further development of GAMSO if there is a need for that.
Also another development could be to determine the information objects handled by GAMSO activities of course keeping in mind the objects that are defined in GSIM.

Conclusion and suggestion: The two standards that are in line with each other (concerning scope, concepts, and coverage) are GSBPM and GSIM, therefore we suggest to concentrate only on these two standards as a scope of this project.

**Comment by FlavioRizzolo** [comment]
We should probably include the definition of Capability as well:

https://github.com/linked-statistics/COOS/issues/7#issuecomment-816858737

**Comment by FranckCo** [comment]
Capability class introduced in commit f8a689e4982041a8be95564101a1bbf13a8e8bcd, question on CSPA roles remaining.

**Comment by JALinnerud** [comment]
TOGAF has a definition of capability: "An ability that an organization, person, or system possesses. Capabilities are typically expressed in general and high-level terms and typically require a combination of organization, people, processes, and technology to achieve."

**Comment by FlavioRizzolo** [comment]
TOGAF is a good reference to follow. 

CSDA definition of capability, loosely based on TOGAF, provides an interesting twist: "Capabilities provide the statistical organisation with the ability _to undertake a specific **activity**_. ". That gives use a link to Activity. Putting everything together, we could define capability in COOS as "an ability a Statistical Organization possesses to undertake a specific Activity".

Also from CSDA: "A capability is only achieved through the integration of all relevant capability elements (e.g. methods, processes, standards and frameworks, IT systems and people skills)"

I like the addition of "methods, processes, standards and frameworks" as capability enablers.
