### ISSUE TITLE
Is Statistical Operation a GSIM Statistical Program?

### ISSUE THREAD

**Issue by FlavioRizzolo** [linked-statistics/COOS#5]
Could the Insee notion of **Statistical Operation** be modeled as a **Statistical Program** or a subclass of it?

**Comment by FranckCo** [comment]
Notes from March 7 meeting:

 - Yes, insee:StatisticalOperation is a subclass of the StatisticalProgram.

**Comment by FranckCo** [comment]
Comments on the March 7 meeting notes:

 - So we create a StatisticalProgram class in the COOS. Do we also create StatisticalOperation, and if yes linked how to StatisticalProgram?

**Comment by FlavioRizzolo** [comment]
GSIM Statistical Programs seem to be an instantiations of StatisticalProductionActivity. See Explanatory Text here: 

https://statswiki.unece.org/display/newclick/Statistical+Program 

"Some examples of Statistical Program are: Labour Force Survey - Multipurpose Household Survey - National Accounts - Demography - Overseas Arrivals and Departures"

**Comment by FranckCo** [comment]
I propose to make coos:StatisticalProgram a sub-class of coos:Activity, because programs may contain activities that are not strictly production or even statistical.

**Comment by FranckCo** [comment]
Decided during July 2 meeting: make  coos:StatisticalProgram a sub-class of coos:StatisticalActivity in order to be coherent with GSIM that explicitly mentions "This does not include statistical support functions such as metadata management, data management (and other overarching GSBPM processes) and design functions. These activities are conducted as part of Statistical Support Programs."

The link with StatisticalSupportProgram is dealt with in issue #4.
